### ISSUE TITLE
No use with today's modern PHP language.

### ISSUE THREAD

**Issue by ghost** [excellentingenuity/EloquentUUID#10]
Please release packages for the current PHP version. There are a lot of developers like myself who won't even use 5 packages anymore.

**Comment by excellentingenuity** [comment]
A PHP 7 version would be great go ahead and make it happen and submit a pull request. It is not currently supporting PHP 7 only because of a dependency has an issue with PHP 7.

**Comment by excellentingenuity** [comment]
This issue has been addressed with Release 1.0.5
