### ISSUE TITLE
Could this be a trait instead

### ISSUE THREAD

**Issue by philippejadin** [excellentingenuity/EloquentUUID#5]
Everything is in the title :-)

**Comment by excellentingenuity** [comment]
If you want to make a compatible trait go ahead, then submit it with a passing unit test as well

**Comment by excellentingenuity** [comment]
A trait has been added in 10e2452 but you still have to set the incrementing property on the eloquent model to ```false``` if you use the trait instead of extending the EloquentUUID or UUIDUser
